### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by talarari** [OrleansContrib/Orleans.StorageProvider.Redis#25]
We have an orleans cluster using azure blob storage for state persistence, We'd like to try redis for better performance.
@martinothamar i see you have a fork with more recent code, including Etag support, what's the status on that? is it going to be merged here? would you consider the fork production ready ?

Also, we're still on orleans 1.5.x is there anyway to use this on 1.5.x? i see @martinothamar version works very differently with lua scripts and etag, support, any advce on how to back port this to 1.5.x?

Thanks!

**Comment by martinothamar** [comment]
Most of the stuff I've done is already merged into the dev branch, some of it can probably be worked into the master branch too (that's tracking 1.5.x I think). 

I should have created an issue on this earlier but forgot. We had some issues with the Redis provider and ultimately moved to SQL server for grain state before going into production. Redis was great most of the time but after a while (days) the StackExchange.Redis package started throwing out exceptions it couldn't recover from, something network related I can't quite remember the specifics of (timeouts or something). There are open issues on that and the team behind it is currently reworking the networking layer with the new System.IO.Pipelines stuff in .NET Core. I'll definitely revisit this once 2.0 reaches the StackExchange.Redis package, since I think Redis makes a good fit with Orleans grains persistence.

There might also be bugs in the stuff I've done in our fork. The latest commit was an attempt at solving the issue that didn't work. I should probably just revert that. If you could review the dev-branch of this repo that would be great. Maybe you can spot something I couldn't. 

Issue: https://github.com/StackExchange/StackExchange.Redis/issues/871

**Comment by amccool** [comment]
see #27
@talarari are you still on Orleans 1.x ?
